name: publish content from GitHub Issue

on:
  # Issueにラベルが追加されたときに実行
  issues:
    types: [labeled]
  workflow_dispatch:

jobs:
  publish:
    # このジョブで利用する権限を指定
    permissions:
      issues: write        # Issue の編集（例: クローズ）を許可
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Issue に 'publish' ラベルが付与されているか確認
      # 'publish' ラベルがなければ、以降の処理をスキップする
      - name: Check issue labels
        if: contains(github.event.issue.labels.*.name, 'publish') != true
        run: exit 0

      # Issueのラベルを'close'に変更し、'publish'を削除する
      - name: Update Issue Label
        run: | 
          gh issue edit ${{ github.event.issue.number }} --add-label "close"
          gh issue edit ${{ github.event.issue.number }} --remove-label "publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}